version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Building.
          command: ./configure
  build:
    docker:
      - run:
          name: Building..
          command: make
  build:
    docker:
       - run:
          name: Building...
          command: make install
